name: Publish Tagged

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish-release-with-binary:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build -r
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            target/release/imgprssr

  publish-container:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish the Container image
        working-directory: .
        run: |
          sudo apt install qemu-user-static
          platarch=linux/arm64/v8,linux/amd64
          podman build --jobs=6 --platform=$platarch --manifest imgprssr:${{ github.event.release.tag_name }} .

      - name: Push Version
        run: podman manifest push imgprssr:${{ github.event.release.tag_name }} ghcr.io/leemartin77/imgprssr:${{ github.event.release.tag_name }}

      - name: Push Latest
        run: |
          podman tag imgprssr:${{ github.event.release.tag_name }} imgprssr:latest
          podman manifest push imgprssr:latest ghcr.io/leemartin77/imgprssr:latest
