name: Test and Build

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
      - run: cargo test --verbose
