name: Test and Build

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "Containerfile"
      - ".containerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - .github/workflows/test.yml
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "Containerfile"
      - ".containerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  container-and-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./e2e_tests/.nvmrc"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: imgprssrtest
          push: false
          platforms: linux/arm64/v8,linux/amd64
      - run: podman run -d -v ./images:/images -p 3000:3000 imgprssrtest
      - run: npm ci
        working-directory: ./e2e_tests
      - run: npm test
        working-directory: ./e2e_tests
