name: Test and Build

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "Containerfile"
      - ".containerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - .github/workflows/test.yml
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "Containerfile"
      - ".containerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - working-directory: ./imgprssr_core
        run: cargo test --verbose
      - run: cargo test --verbose

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - working-directory: ./imgprssr_core
        run: cargo build --verbose
      - run: cargo build --verbose

  container-and-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./e2e_tests/.nvmrc"
      - run: podman build -t imgprssrtest .
      - run: podman run -d -v ./images:/images -p 3000:3000 imgprssrtest
      - run: npm ci
        working-directory: ./e2e_tests
      - run: npm test
        working-directory: ./e2e_tests
