name: Test and Build

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "Containerfile"
      - ".containerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - .github/workflows/test.yml
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "Containerfile"
      - ".containerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  container-and-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./e2e_tests/.nvmrc"
      - run: |
          sudo apt update
          sudo apt install qemu-user-static
          platarch=linux/amd64
          buildah build --platform=$platarch --manifest imgprssrtest .
      - run: podman run -d -v ./images:/images -p 3000:3000 imgprssrtest
      - run: npm ci
        working-directory: ./e2e_tests
      - name: Test Volume Mount
        run: IMGPRSSR_URL=http://127.0.0.1:3000 npm test
        working-directory: ./e2e_tests
